C:/Users/limef/Documents/randar/.venv/Scripts/python.exe C:/Users/limef/Documents/randar/eval_c2i.py --config "configs/randar_cifar10_random_order.yaml" --ar_ckpt "results/random_order/train_state_early_stop.pt" --data-path "data/latents/cifar10c/severity_1/cifar10c-vq-vae-512-32_codes" --output-json results/random_order/eval_metrics_severity_1.json
C:/Users/limef/Documents/randar/.venv/Scripts/python.exe C:/Users/limef/Documents/randar/eval_c2i.py --config "configs/randar_cifar10_random_order.yaml" --ar_ckpt "results/random_order/train_state_early_stop.pt" --data-path "data/latents/cifar10c/severity_2/cifar10c-vq-vae-512-32_codes" --output-json results/random_order/eval_metrics_severity_2.json
C:/Users/limef/Documents/randar/.venv/Scripts/python.exe C:/Users/limef/Documents/randar/eval_c2i.py --config "configs/randar_cifar10_random_order.yaml" --ar_ckpt "results/random_order/train_state_early_stop.pt" --data-path "data/latents/cifar10c/severity_3/cifar10c-vq-vae-512-32_codes" --output-json results/random_order/eval_metrics_severity_3.json
C:/Users/limef/Documents/randar/.venv/Scripts/python.exe C:/Users/limef/Documents/randar/eval_c2i.py --config "configs/randar_cifar10_random_order.yaml" --ar_ckpt "results/random_order/train_state_early_stop.pt" --data-path "data/latents/cifar10c/severity_4/cifar10c-vq-vae-512-32_codes" --output-json results/random_order/eval_metrics_severity_4.json
C:/Users/limef/Documents/randar/.venv/Scripts/python.exe C:/Users/limef/Documents/randar/eval_c2i.py --config "configs/randar_cifar10_random_order.yaml" --ar_ckpt "results/random_order/train_state_early_stop.pt" --data-path "data/latents/cifar10c/severity_5/cifar10c-vq-vae-512-32_codes" --output-json results/random_order/eval_metrics_severity_5.json

C:/Users/limef/Documents/randar/.venv/Scripts/python.exe C:/Users/limef/Documents/randar/eval_calibration_sample_level.py --config "configs/randar_cifar10_random_order.yaml" --ar_ckpt "results/random_order/train_state_early_stop.pt"
C:/Users/limef/Documents/randar/.venv/Scripts/python.exe C:/Users/limef/Documents/randar/eval_calibration_token_level.py --config "configs/randar_cifar10_random_order.yaml" --ar-ckpt "results/random_order/train_state_early_stop.pt"

C:/Users/limef/Documents/randar/.venv/Scripts/python.exe C:/Users/limef/Documents/randar/eval_c2i.py --config "configs/randar_cifar10_random_order.yaml" --ar_ckpt "results/random_order/train_state_early_stop.pt" --data-path "data/latents/cifar10/test/cifar10-vq-vae-512-32_codes" --output-json results/random_order/basic_eval_metrics.json